name: build
on:
  workflow_dispatch:
  push:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.13'

    - name: Install Requirements
      run:  |  # Custom pyinstaller built with https://github.com/yt-dlp/pyinstaller-builds
          python devscripts/install_deps.py -o --include build
          python devscripts/install_deps.py --include curl-cffi
          python devscripts/install_deps.py --include brotlicffi
          python devscripts/install_deps.py --include websocket
          python devscripts/install_deps.py --include requests
          python devscripts/install_deps.py --include pycryptodomex
          python devscripts/install_deps.py --include phantomjs
          python -m pip install -U "https://yt-dlp.github.io/Pyinstaller-Builds/x86_64/pyinstaller-6.11.1-py3-none-any.whl"

    - name: Bump Version
      id: bump_version
      run: python devscripts/update-version.py

    - name: Build Lazy Extractors
      id: lazy_extractors
      run: python devscripts/make_lazy_extractors.py

    - name: Run PyInstaller Script
      run: |
          python -m bundle.pyinstaller
          python -m bundle.pyinstaller --onedir

    - name: Upload Package Artifacts
      uses: actions/upload-artifact@master
      with:
        name: pkg-artifacts
        path: dist/yt-dlp.exe
        compression-level: 0

    - name: Delete tag
      run: gh release delete latest --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Packages
      id: upload_release
      uses: svenstaro/upload-release-action@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/yt-dlp.exe
        asset_name: yt-dlp.exe
        tag: latest
        overwrite: true
